### ISSUE TITLE
mac m1 build error

### ISSUE THREAD

**Issue by ioo0s** [TorqueGameEngines/Torque3D#1026]
build command
```
cmake .. -DTORQUE_APP_NAME=test
make
```
error info:
```
path/to/Torque3D/Engine/lib/sdl/src/file/cocoa/SDL_rwopsbundlesupport.m:45:20: fatal error: mixing declarations and code is incompatible with standards before C99 [-Wdeclaration-after-statement]
    NSFileManager* file_manager = [NSFileManager defaultManager];
                   ^
1 error generated.
make[2]: *** [Tools/CMake/sdl2/CMakeFiles/SDL2-static.dir/src/file/cocoa/SDL_rwopsbundlesupport.m.o] Error 1
make[1]: *** [Tools/CMake/sdl2/CMakeFiles/SDL2-static.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by WageCrusader** [comment]
I was able to reproduce this issue and have found that it is resolved by updating the SDL files in Engine/lib/sdl to the newest release, obtainable at their repo [(libsdl-org/SDL)](https://github.com/libsdl-org/SDL/releases/tag/release-2.26.5).
I believe there is a PR in place [here](https://github.com/TorqueGameEngines/Torque3D/pull/1027)

**Comment by Azaezel** [comment]
Unfortunately, it would appear a straight upgrade has negative side effects on the Unix side. we are looking into a solution, however.

**Comment by WageCrusader** [comment]
I believe https://github.com/TorqueGameEngines/Torque3D/pull/1032 solves this issue

**Comment by Azaezel** [comment]
To be clear: https://github.com/TorqueGameEngines/Torque3D/pull/1050 (even newer version of sdl) also resolves the issue, and should work for actual games, we're just trying to track down why the CI unit tests specifically are having a fit before we roll that on in.
