### ISSUE TITLE
Fmod Studio implementation

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#104]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/1099)).
The issue was originally created by @galek and had a total of 2 comments that may contain additional information. The original issue description is pasted below:

FMODex is already deprecated.

Current fmod version is fmod studio

**Comment by JeffProgrammer** [comment]
FMODex has been removed. the new one is called 'FMOD Core' now over studio.

**Comment by Zbig281** [comment]
Any guide on how to use Fmod for torque3d version e.g. 3.5.1?
