### ISSUE TITLE
The getcount method is not work

### ISSUE THREAD

**Issue by JaxonShao** [TorqueGameEngines/Torque3D#1042]
I use the 4.03 engine to create the coin collection 4.0tutorial game. The getcount method is not work, and the game ends when I pick up the first coin. The game is normal when I use Global variable.
![QQ图片20230705054515-2](https://github.com/TorqueGameEngines/Torque3D/assets/135344192/c1954b2c-a107-468e-ab56-a271ca419a9d)

**Comment by lukaspj** [comment]
Typo, it should be `Coins.getCount()`, the name of the SimGroup/folder created in the editor:
https://docs.torque3d.org/getting-started/getting-familiar/your-first-game/adding-a-coin
![image](https://github.com/TorqueGameEngines/Torque3D/assets/2369614/07d8ae03-896d-49a9-beac-4a95422f41a8)
