### ISSUE TITLE
skeleton mesh‘s shape editor can’t  save after restart main world editor！

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#1048]
skeleton mesh‘s shape editor can’t  save after restart main world editor！

condition：
1.mesh and animation from Mixamo and its .dae file

but its weird that in 3.10.1 ver‘s demo project the “soldier_rigged.DAE” can save after restart world editor（in 3.10.1）,
And i can’t restore   “soldier_rigged.DAE”  to 4.0.3 ver‘s shape editor because can't apply animation it report error (general understanding of UX).
So i cant find a alternative workflow of animation of skeleton mesh for the 3.10.1 and 4.0.3

issue may connect to:
#1047 
[https://github.com/TorqueGameEngines/Torque3D/issues/1047#issue-1794787230](url)

#1043 
[https://github.com/TorqueGameEngines/Torque3D/issues/1043#issue-1789218604](url)

step and output info:
![01](https://github.com/TorqueGameEngines/Torque3D/assets/109895629/8bf1f091-e292-4c0c-8460-6f7624e3cbcc)

![02](https://github.com/TorqueGameEngines/Torque3D/assets/109895629/9b2be592-f081-4f2a-a06b-0441f56db716)

**Comment by ghost** [comment]
> 骨架网格体的形状编辑器在重新启动主世界编辑器后无法保存！
> 
> 条件：1.来自Mixamo及其.dae文件的网格和动画
> 
> 但奇怪的是，在 3.10.1 Ver 的演示项目中，“soldier_rigged。DAE“可以在重新启动世界编辑器（在 3.10.1 中）后保存，并且我无法恢复”soldier_rigged。DAE“到 4.0.3 版本的形状编辑器，因为无法应用动画它报告错误（对 UX 的一般了解）。所以我找不到 3.10.1 和 4.0.3 的骨架网格动画的替代工作流程
> 
> 问题可能连接到： #1047 [https://github.com/TorqueGameEngines/Torque3D/issues/1047#issue-1794787230](url)
> 
> #1043 [https://github.com/TorqueGameEngines/Torque3D/issues/1043#issue-1789218604](url)
> 
> 步骤和输出信息： ![01](https://user-images.githubusercontent.com/109895629/251938815-8bf1f091-e292-4c0c-8460-6f7624e3cbcc.jpg)
> 
> ![02](https://user-images.githubusercontent.com/109895629/251938817-9b2be592-f081-4f2a-a06b-0441f56db716.jpg)

im sorry that i found before you can save info ,you should nav to the module make sure has two lines or fill two lines(**not shown in the module properties in the 4.0.3 editor** ):
before:
`<DeclaredAssets
        Extension="asset.taml"
        Recurse="true"/>`

after filled:
`<DeclaredAssets
        canSave="true"
        canSaveDynamicFields="true"
        Extension="asset.taml"
        Recurse="true"/>` 

ps：i referenced from community project：FPSplayer [https://github.com/Torque3DResources/FPSPlayer](url)  it may contents best-practice how-to somehow. recommend that take action after full systematically review it.
steps：

![01](https://github.com/TorqueGameEngines/Torque3D/assets/109895629/7bc39b14-7ecd-4f64-b033-1dab23dc8285)
![02](https://github.com/TorqueGameEngines/Torque3D/assets/109895629/9d3a05d3-2649-45bc-83c3-e3c7bb0bb6fe)
![03](https://github.com/TorqueGameEngines/Torque3D/assets/109895629/d8ae3813-a2ed-4a10-a52f-de833ffb79d4)

**Comment by Areloch** [comment]
I've been trying to replicate this but not really having much luck. 

To be sure I'm following along right, the steps would be:

1) Have a character model imported in
2) Add a new animation to it, click the save button
3) Close the editor, then re-open it and the new animation is gone
4) edit the DeclaredAssets define on the module the character model asset is in to have the canSave values as true
5) Re-add the new animation, and it saves properly

If the above is all correct steps, Is it possible you can upload the shown art somewhere so I can try to replicate it this end? Also what version of T3D is it?

**Comment by ghost** [comment]
> I've been trying to replicate this but not really having much luck.
> 
> To be sure I'm following along right, the steps would be:
> 
> 1. Have a character model imported in
> 2. Add a new animation to it, click the save button
> 3. Close the editor, then re-open it and the new animation is gone
> 4. edit the DeclaredAssets define on the module the character model asset is in to have the canSave values as true
> 5. Re-add the new animation, and it saves properly
> 
> If the above is all correct steps, Is it possible you can upload the shown art somewhere so I can try to replicate it this end? Also what version of T3D is it?

hi,i feel sorry, i can't restore it now too,even  after i start a virtual mechine of win10.
thank your for time,but i actually encounter it in 3.10.1 and 4.0.3 and i don’t know why.
but one can have a try if encounter “can't save”，
thank community and i feel sorry about it.

**Comment by Areloch** [comment]
No worries, sorry I couldn't be more of a help there.
Hopefully it doesn't come back up in the future and then neither of us have to worry about it :)

I'll go ahead and close this for now then, but if it crops back up again, feel free to make another issue report!
