### ISSUE TITLE
Possible redundant code in scatterSkyP.hlsl

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#116]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/1039)).
The issue was originally created by @RichardsGameStudio and had a total of 1 comments that may contain additional information. The original issue description is pasted below:

In shaders/common/scatterSkyP.hlsl there are 2 lines of code which don't do anything.

   float4 nightSkyColor = texCUBE( nightSky, -In.v3Direction );
   nightSkyColor = lerp( nightColor, nightSkyColor, useCubemap );

   float fac = dot( normalize( In.pos ), sunDir );//<== REDUNDANT?
   fac = max( nightInterpAndExposure.y, pow( saturate( fac ), 2 ) );//<== REDUNDANT?
   Out = lerp( color, nightSkyColor, nightInterpAndExposure.y );

   Out.a = 1;

As far as I can see they can be removed, because fac isn't used anywhere.

**Comment by Azaezel** [comment]
fars I can tell from
![Untitled](https://user-images.githubusercontent.com/4236451/84577350-1b61c480-ad81-11ea-958f-e15f1ce093d3.jpg)
![Untitled2](https://user-images.githubusercontent.com/4236451/84577351-1c92f180-ad81-11ea-9a41-954b1fa03f36.jpg)

fac is an attempt at tossing the value into the same colorspace

**Comment by Azaezel** [comment]
resolved
