### ISSUE TITLE
Is The Forge going to be used as a renderer for T3D?

### ISSUE THREAD

**Issue by HumanGamer** [TorqueGameEngines/Torque3D#1164]
I noticed on the GitHub for The Forge rendering framework in the readme is says that Torque3D will be using The Forge. Is this true? https://github.com/ConfettiFX/The-Forge?tab=readme-ov-file#torque-3d
This seems to be the only place it's mentioned.

**Comment by Azaezel** [comment]
No. It was noted that one of our contributors was looking into it at one time, publicly, and folks blew that out of proportion. There are no remaining notes left by said contributor. There are no current plans to work around the redundancies added since that was first reviewed.
