### ISSUE TITLE
AIPlayers still do not always pick the correct action animation

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#120]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/968)).
The issue was originally created by @GuyAllard and had a total of 0 comments that may contain additional information. The original issue description is pasted below:

see [this thread](https://www.garagegames.com/community/forums/viewthread/130955) for a description of the problem and some investigation into the cause of the issue. This is possibly related to ticket #145

**Comment by Azaezel** [comment]
resolved
