### ISSUE TITLE
Cannot set the resolution in windowed mode

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#122]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/946)).
The issue was originally created by @lukaspj and had a total of 1 comments that may contain additional information. The original issue description is pasted below:

Setting the resolution in windows mode doesn't work at the higher resolutions. Try setting it to the full resolution of the desktop while in windowed mode. It doesn't work unless you go fullscreen and then alt-enter out of it.

**Comment by Azaezel** [comment]
on this one, the last (largest) should probably trip borderless windowed mode.
