### ISSUE TITLE
TorqueScript unit tests

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#130]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/866)).
The issue was originally created by @crabmusket and had a total of 0 comments that may contain additional information. The original issue description is pasted below:

To ensure we don't break TS compatibility - hopefully.

**Comment by JeffProgrammer** [comment]
we got these now!
