### ISSUE TITLE
Object IDs don't reset after disconnecting

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#168]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/356)).
The issue was originally created by @deadlyduckuk and had a total of 6 comments that may contain additional information. The original issue description is pasted below:

see this thread
http://www.garagegames.com/community/forums/viewthread/133893

**Comment by JeffProgrammer** [comment]
I think we should still not recycle ids. It could break potential isObject or potentially other issues where an id was being used in the past and now its being used again for a different class instance, leading to subtle bugs (especially in legacy code). I propose we make it go to a S64 so we do not have to worry about running out, as well as maybe updating the scripting engine to use 64bit ints? Thoughts @Areloch @jamesu

**Comment by JeffProgrammer** [comment]
A few of us discussed this, as noted in the original thread on the forums, it's best to keep them not recycled as it could cause bugs when checking if an object exists. Solution to running out of ids is to use object pooling (which should be done).
