### ISSUE TITLE
Issue for playAudio with FMOD Event

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#169]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/281)).
The issue was originally created by @mquaker and had a total of 0 comments that may contain additional information. The original issue description is pasted below:

i create and loaded FMOD Project(.fev) and Bank(.fsb) FMOD Designer.
works fine on shapebaseimage's stateSound and ExplosionData's soundProfile.

'ShapeBase.playAudio' and 'GameConnection.play3D' method don't play FMOD Event.

**Comment by JeffProgrammer** [comment]
FMODex has been removed.
