### ISSUE TITLE
When FMOD is used on client, it is also required on dedicated server

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#173]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/169)).
The issue was originally created by @DavidWyand-GG and had a total of 2 comments that may contain additional information. The original issue description is pasted below:

If FMOD support has been compiled into a client, then it must also be compiled into a dedicated server (such as under Linux).  T3D's FMOD code adds three additional Datablocks:
- SFXFMODEvent
- SFXFMODEventGroup
- SFXFMODProject

This expands the Datablock class table that is used by T3D's networking.  If the dedicated server is not compiled with FMOD support then these Datablocks will not be a part of the server's class table.  When the class table is out of sync between a client and server, bad things happen (usually the client will Assert in strange places or crash).

It would be great if a dedicated server can be compiled with FMOD stubs without needing the FMOD library to be in place to at least allow the class tables to be in sync.

**Comment by JeffProgrammer** [comment]
We should probably remove the old FMOD support. That used the legacy FMOD ex which is over 10 years old.

**Comment by JeffProgrammer** [comment]
FMODex has been removed.
