### ISSUE TITLE
HDR does not treat the sun as bright

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#179]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/4)).
The issue was originally created by @crabmusket and had a total of 1 comments that may contain additional information. The original issue description is pasted below:

**Build:** 1.2 confirmed, though I've seen it happen for as long as we've had HDR
**Platform:** Windows 7 64 bit
**Target:** PostFX
**Issue:** HDR does not treat the sun as a bright object

Something I've noticed for a while and been meaning to ask about. When you turn HDR on and start at the sun, everything gets really bright, presumably because the HDR shader doesn't register the sun as a 'bright' object. Is there anything we can do about this?

**Reproduction:** Open up Empty Terrain from the Full template, add HDR via the PostFX manager, look at the sun. Everything becomes brighter when it should become dimmer.

As described [here](http://www.garagegames.com/community/forums/viewthread/131715)

**Comment by Azaezel** [comment]
RnD note: https://github.com/TorqueGameEngines/Torque3D/blob/Preview4_0/Templates/BaseGame/game/core/rendering/shaders/scatterSkyP.hlsl#L66

**Comment by Azaezel** [comment]
resolved
