### ISSUE TITLE
Replace incompatible PBR materials

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#184]
The PBR example assets are incompatible with open source projects, they are only free to use and cannot be re-distributed on their own: https://freepbr.com/about-free-pbr/

So I would suggest replacing them with materials that are open source compatible:
For example from here https://cc0textures.com/

**Comment by Bloodknight** [comment]
If there are assets from freePBR it might just be worth asking him specifically, game engines are a bit of a grey area between using and distributing, a 'business to business' discussion might be worth chatting over.

**Comment by ghost** [comment]
There is no grey area, either it is an open source compatible license or not, there is also nothing to discuss, if he makes an exception for us, he might as well just make it all public domain, as there would be no difference anymore.

**Comment by ghost** [comment]
Well better not replace them, but remove them, see my suggestion here: https://github.com/TorqueGameEngines/Torque3D/issues/194 test projects should not be in the main repo or main game anyway.

**Comment by Areloch** [comment]
I'll do up a set of materials this weekend to go into a 100% definitively no-issues involved version of the module, but for now to be safe the concerning content has been removed from the repo

**Comment by ghost** [comment]
Please don't touch the art assets again, let me do it and you do things you are good at that are more important.

**Comment by Areloch** [comment]
You are free to contribute art assets you feel are a good contribution via a Pull Request. If I have any art I feel would be a valid inclusion, I can do the same.

**Comment by ghost** [comment]
I thought we were at the point now where we say the art assets should not be in the main repo in the main template to begin with, but as addons and for that you need to create a place and a way for people to contribute first.

**Comment by Azaezel** [comment]
Dependent sub repositories for that and the project manager are being worked on as we speak. 
https://github.com/TorqueGameEngines/Torque3D/pull/197 is one of those interlocking plugin support features being fleshed out so folks can pick and choose the bits they want to drop into the data directory from a gui and have it 'just work' (within reason).

Also hashing out notions with the T2D dev crew to see about similar support for them.
