### ISSUE TITLE
Bring back old templates

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#185]
You should not break backwards compatibility, especially without having a production ready replacement.  By doing this you are throwing everyone that uses any old version of Torque overboard, with no way of upgrading their project, except than basically rebuilding it all file by file.

The new module system looks absolutely horrible at first glance, it may have its advantages, but you cannot just force everyone to use a new system that has never been proven to work, while taking away a system that has been proven to work.

The folder is called "templates" which is plural and the engine should work independently with multiple templates.

You should only remove old templates, if the new ones are bug free and have been used to make production ready games, otherwise you never know, if you are developing into a dead end.

**Comment by Azaezel** [comment]
no.
