### ISSUE TITLE
Is Kork open source?

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#186]
I noticed you added Kork, but I never saw him being released as open source, you should verify license compatibilities before you just randomly add stuff.

**Comment by Areloch** [comment]
I'm fairly certain there's no license issue, but it is indeed unneeded extra bloat to the repo what could easily separate. It has been removed from the repo.

**Comment by ghost** [comment]
Well to go nitpicking, everything that was not in the MIT release of the engine, has not been released as MIT, so therefore there is a license issue, the thing is just, that there is probably nobody left to complain. It is in a binary format as well, so no open source version is available.

**Comment by Areloch** [comment]
A multitude of original content was provided to me by GG to turn into MIT-licensed content packs, such as the old Burg demo, the Pacific demo, Deathball Desert, etc. Many legacy pieces of art including the Gideon model were included with this. I beleive Kork was also included, but I would need to go double check the original files provided to me from GG themselves to be sure before I were to include him again.

**Comment by ghost** [comment]
Kork is only in binary .dts format, while the original MIT assets were only distributed into the engine in the source .dae collada format. Something being binary only is a sign of it not being open source.
