### ISSUE TITLE
TTR assets probably incompatible

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#187]
I noticed a folder called TTR, it contains a level from an Unreal Tournament mod called "The Third Reich", even if Jeff was a creator of the mod, it is still very unlikely that the assets are licensed as open source.

You cannot just dump everything into a git repo, git is supposed for open source projects, by the way the level does not fulfill any purpose anyway, it has graphic issues and cannot be played. The visuals are also outdated by like two decades, it is a bad choice to use for testing or show off.

**Comment by Areloch** [comment]
They are infact, under my jurisdiction to use. However, yes, that module has outlived it's usefulness and will be removed.

**Comment by ghost** [comment]
Being allowed to use it and it being open source compatible are two different things. Why are you committing test art assets to the primary repository anyway? When I was on the steering committee we carefully planned not to litter the main repo with useless art assets that eat a lot of memory. Git is version control and things will be there forever, there is no removing.

**Comment by Areloch** [comment]
We'll chalk it up to a clerical error. The concerning content has been removed from the repo.

**Comment by ghost** [comment]
Just to remind you that "clerical error" was 100MB of useless and probably even illegal junk added to the main repo.

**Comment by Areloch** [comment]
The TTR content was not illegal as the entirety of the original mod was put in my stewardship to use as seen fit.
And I did not forget, nor require a reminder. It was a clerical error, and has been corrected and won't be repeated.

**Comment by ghost** [comment]
You cannot correct such errors, at least that is how I think Git works, it is version control and things committed are in there forever. I think the only way to correct such errors is to delete the branch without ever merging it with the main repo, then the history will be deleted, otherwise you increased the size of the main repo by 100 useless Megabytes for eternity.

**Comment by Areloch** [comment]
You are incorrect in this case. While it's not something to be done lightly because it can have impacts on stuff like unmerged PRs and the like, it is possible to re-history the repo and remove files from it entirely, not just do a delete action. That's what I did on the offending modules in question.

**Comment by ghost** [comment]
Then I take your word for it, I never touched the advanced git functions.
