### ISSUE TITLE
Trying to change controls results crash

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#188]
I tried to change the controls in options -> keyboard and mouse and when clicking on it, the whole game crashes to desktop.
Console says:
data/ui/scripts/controlsMenu.cs (134): Unable to find object: 'moveMap' attempting to call function 'getBinding'

**Comment by Azaezel** [comment]
Being worked on this week.

**Comment by Azaezel** [comment]
https://github.com/Azaezel/Torque3D/commit/ac395775439985cc7332e777485d252055bdb042
may fix that. Working a few additional kinks out.

**Comment by Azaezel** [comment]
resolved
