### ISSUE TITLE
Verve editor cannot be closed

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#189]
I clicked on the Verve editor symbol in the world editor and it opened the Verve editor, but it cannot be closed, you have to kill the whole game with alt+F4 to get out.

**Comment by Bloodknight** [comment]
If you focus the main torque window you can then click the verve icon again to close it without killing the entire engine process. 
Inability to kill the window itself is definitely an issue

**Comment by ghost** [comment]
Ok, this really works, still confusing.

**Comment by Areloch** [comment]
#259 Fixes it, just needs to be validated and merged

**Comment by Azaezel** [comment]
verified fixed
