### ISSUE TITLE
Bad default postFX settings

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#190]
No idea why nobody notices, but the default settings for postFX are extremely bad, everything is glowing extremely and the DOF is so blurry, you cannot see anything clearly except you directly look at it close and to top it off, there is not even a way to turn it off in the regular options menu.

**Comment by Bloodknight** [comment]
There was a known bug with one of two of the postFX (unsure of DX/GL status) others are mostly just a matter of needing an artist with a good eye to fix and PR the settings.

**Comment by ghost** [comment]
The problem is, the postFX editor is broken, as well as the graphic options menu where you cannot even turn the postFX off, so you should just disable postFX until you have a working editor and working options where you actually can turn them on and off, instead of being forced to get eye cancer.
