### ISSUE TITLE
Move modules to a different repository

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#194]
If you want to make the engine modular, then the modules should be removed from the main repo.

Github is not meant for art assets and you cannot commit your 100MB test level to the main repo every time, just because you want to test something once and then "remove" it.

Having it modular allows the modules being developed independendly by others, which gives them more freedom.

It was already decided when I was still at the steering committee, that no more art assets should be committed to the main repo, except minor small files, like examples, GUI images etc since the main repo was already unnceccesarily big with all the art assets.

**Comment by Azaezel** [comment]
"If you want to make the engine modular, then the modules should be removed from the main repo."

We quite literally discussed doing just that last night in discord with the fps example as a demonstration for a porting guide/ acid test for the upcoming project manager, as has always been the plan. It'll take a bit.

**Comment by ghost** [comment]
Well to me it looks like this is not the plan, since there are constantly "test" modules being added to the main repo, which should not happen.

**Comment by Azaezel** [comment]
What part of preview in the very name of the fork is at all unclear. This convos exhausted it's utility. Question asked, question answered. Keeping this issue around as it is still on the todo list, but don't expect further responses on the matter until the prepwork is done on it..

**Comment by Areloch** [comment]
Was more or less a clerical error that left the various test modules in the repo. I'll take the blame for that one for brainfarting cleaning them out before the hop-over was done.
I've now removed the unneeded extra modules from the repo and as suggested the plan is to put them in separate repos going forward.
