### ISSUE TITLE
Removing templates and redesigning compiling workflow

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#195]
If you plan to no longer have templates, then you might as well just remove the Templates folder completely.
Why you need a "Templates" folder, when there are no templates and probably never will be, since you now want it modular?
If you are at it, you could also remove the "My Projects" folder, since that old workflow does not work anymore anyway, since we no longer have a project manager.
You can even remove the BaseGame template from the main repo and change the way the engine is compiled.
What I always do to compile my game is, that I compile the engine and then place the compiled binaries and libs manually into my game folder, because the old way of doing it is broken anyway.
If you want to redesign everything you might as well just go all the way.
My suggestion would be to have an "Engine" repo, a "BaseGame" repo and one or multiple "modules" repos allthough I'm not sure about separating the BaseGame and Engine yet.

**Comment by Bloodknight** [comment]
If you were part of the discord community you would have been able to participate in the multiple discussions there have been on this very topic, also where people infinitely smarter could correct you on the 'it doesn't work anyway' and 'it's all broken anyway' sarcastic-vitriol

**Comment by Areloch** [comment]
While there is a single template by default in the engine now(as having multiples was just an obscene amount of duplicated files and extra maintenance effort) there is still plenty of room and justification for teams and projects to make their own templates for their specific needs which can then be used as normal via the switch.
If we were completely dropping the idea of templates, then the suggested changes wouldn't be bad, but as said, templates are still a thing, it's just there's only one that ships with the engine as default now to avoid additional files and maintenance upkeep.

**Comment by ghost** [comment]
But when I suggested, to add the old templates back, I was told "no". So only templates based on the new "BaseGame"? If you stick with the idea of a very basic BaseGame, then you will never have different templates, since the base game is the base, that will hardly ever be changed and the rest is all modular.

**Comment by Areloch** [comment]
And as I said, the template functionality is there for whatever a production/team may need. They are free to make their own templates preconfigured to what they need to save time.
Production requirements are often distinct from general-purpose usage, so supporting it and not filling the engine with a dozen templates aren't mutually exclusive

**Comment by ghost** [comment]
Do you really think there will ever exist a production team that uses Torque3D, that will use the new version and that will create new templates? Just saying that it is extremely unlikely for this case to exist and even if for the rare case it exists, they would just change the template once, then work with it and never bother with it again.
But whatever one additional Folder is not going to do much damage nor will it help much.
