### ISSUE TITLE
Where are PBR materials sliders?

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#196]
In an old dicussion about PBR I was told the new textures will need metalness, roughness etc textures to work with PBR, but on further questioning, if there will be a method to do it on the fly without having those layers I was told there will be sliders or manual settings where you can say "this texture is 80% rough and 25% metallness" Sure this will not be as good as a proper texture, but it probably gets close and will give you a good compromise, it will at least be good enough for testing and prototyping.

Now I see there is no such feature. Is it that hard to program or what is the reason? We already have a color picker for materials, which is mostly useless, but having such a picker for metalness or roughness would be useful, it just needs to be in the range from black to white.

**Comment by Bloodknight** [comment]
![image](https://user-images.githubusercontent.com/1765910/83629861-c2c94500-a592-11ea-84a7-c9d6e90f6c30.png)

**Comment by ghost** [comment]
Well they are not there for me, I use the "Preview4_0_bld5_win" build.
Ah I foung it, it is now hidden within "Lighting Properties" further below.
