### ISSUE TITLE
Using setTransform() to move a listener into an SFXSpace can corrupt SFXWorld:: mScopeStack

### ISSUE THREAD

**Issue by chaigler** [TorqueGameEngines/Torque3D#203]
Using setTransform() to reposition a listener (i.e. a player) in range of an SFXSpace can corrupt SFXWorld::mScopeStack by adding more objects to the stack than will be removed when the listener leaves the area. This will cause a crash once enough objects are added to the stack.

Original issue was noted here with steps on how to reproduce and a suggested fix: http://www.garagegames.com/community/forums/viewthread/129864

But still appears to be an issue: https://forums.torque3d.org/viewtopic.php?f=2&t=1621

**Comment by Azaezel** [comment]
resolved
