### ISSUE TITLE
IBLUtilities drawPrimitive

### ISSUE THREAD

**Issue by rextimmy** [TorqueGameEngines/Torque3D#205]
I noticed this bug in our build the other day and you guys have the same, the primitive count here is wrong (this was my bad) https://github.com/TorqueGameEngines/Torque3D/blob/Preview4_0/Engine/source/T3D/lighting/IBLUtilities.cpp#L77 & here https://github.com/TorqueGameEngines/Torque3D/blob/Preview4_0/Engine/source/T3D/lighting/IBLUtilities.cpp#L180  Primitive count should be 1, 3 is the vertex count :)

**Comment by Azaezel** [comment]
resolved
