### ISSUE TITLE
Module system breaks zip support

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#22]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/2176)).
The issue was originally created by @chaigler and had a total of 1 comments that may contain additional information. The original issue description is pasted below:

The new module system pulled in from T2D fails to load modules from a zipped archive. Console log shows something similar to:

> Module Manager: Cannot load explicit module Id 'CoreComponentsModule' as it does not exist.

This occurs on the latest development branch using the new (BaseGame) template. 

The odd thing is a game will still work if the 'data' folder is left out of the zip (only 'core' and 'tools' go in game.zip) despite the warnings about not being able to load the Core & Tools modules. Putting the 'data' folder in the zip just results in the engine running with a blank screen.

**Comment by chaigler** [comment]
@lukaspj Believe we can close this one. Was addressed in #449
