### ISSUE TITLE
Add console prefs for the console log to also list timestamps when messages are emitted

### ISSUE THREAD

**Issue by Areloch** [TorqueGameEngines/Torque3D#220]
A pref for if it emits on server, client, or both as well as a pref for None, Explicit Timestamp and Delta timestamp.
The pref can be set in the main.cs to dictate behavior.

Jozor noted http://www.garagegames.com/community/forums/viewthread/60254/1#comment-448812 as an example case for building the timestamp

**Comment by Bloodknight** [comment]
if we are looking at reviewing the logging a bit, can we also add the ability to dump warns/errors to a separate file each? 

Also, to have those files auto-flushed so you can access them in real-time as the engine./game is running?
