### ISSUE TITLE
Terrain material oddities

### ISSUE THREAD

**Issue by Bloodknight** [TorqueGameEngines/Torque3D#224]
When creating terrain material assets, the system creates a taml file and a <materialname>.cs file as expected, but the terrain system doesn't find the material unless you add the material to the autorun materials.cs file, so it constantly reloads all materials as warning_material

**Comment by Azaezel** [comment]
Design Intent Note: terrain files themselves should be genning a taml, and listing used terrain materials as dependencies. That way we only load up relevant mats. (the materialis.cs recursive search and exec mechanism loads up all of em, which is why that's a valid workaround)

**Comment by Azaezel** [comment]
fixed
