### ISSUE TITLE
TerrainBlock::_onZoningChanged can cause a crash under certain conditions

### ISSUE THREAD

**Issue by chaigler** [TorqueGameEngines/Torque3D#230]
Here's an odd one I ran into today:

Place two terrains in the same position with a zone object in range of both. Hide one of the terrains. Save, restart the level, open the world editor and the engine will crash in:
```
void TerrainBlock::_onZoningChanged( SceneZoneSpaceManager *zoneManager )
{
   if ( mCell == NULL || zoneManager != getSceneManager()->getZoneManager() )
      return;

   mZoningDirty = true;
}
```
Believe the problem is getSceneManager() returning null for the hidden terrain (obviously - it's not 'in' a scene manager once hidden). 

Thinking the fix is just adding a check to make sure getSceneManager() & getZoneManager() != NULL in the if statement.

**Comment by chaigler** [comment]
I modified TerrainBlock::_onZoningChanged() in my repo. No issues so far with this version:

```

void TerrainBlock::_onZoningChanged( SceneZoneSpaceManager *zoneManager )
{
   const SceneManager* sm = getSceneManager();

   if ( mCell == NULL || (sm != NULL && sm->getZoneManager() != NULL && zoneManager != sm->getZoneManager()) )
      return;

   mZoningDirty = true;
}
```

**Comment by Azaezel** [comment]
reproduced by shoving a couple terrains and a zone as stated. the second a zone portal was spawned, hit the crash. 
can confirm resolution via
```
   const SceneManager* sm = getSceneManager();
   if ( mCell == NULL || ((sm) && (sm->getZoneManager()) && (sm->getZoneManager() != zoneManager)) )
      return;
```
As an additional note, pre-popping open the editor, hidden was *not* applied to the hidden terrain. Did you have additional code lurking around to correct that aspect as well we should throw into a PR, or will we need to do a bit of rooting around?
