### ISSUE TITLE
BaseGame crashes when switching to FullScreen from main menu

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#34]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/2105)).
The issue was originally created by @nev7n and had a total of 0 comments that may contain additional information. The original issue description is pasted below:

Steps to reproduce:
- Build with BaseGame template
- Run executable
- Select options from main menu, then graphics settings
- Tick Fullscreen, click OK

Crashes in gfxD3D11Device.cpp, line 828:
`mD3DDeviceContext->PSSetShader(mLastPixShader, NULL, 0);`

Unhandled exception at 0x747FB872 (KernelBase.dll) in BaseGame_DEBUG.exe: 0x0000087D (parameters: 0x00000000, 0x0073C420, 0x0073B858). occurred

The problem doesn't occur if you switch to fullscreen in game after you've loaded a mission

**Comment by Azaezel** [comment]
resolved
