### ISSUE TITLE
Leveraging std:: machinery

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#43]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/1964)).
The issue was originally created by @elfprince13 and had a total of 5 comments that may contain additional information. The original issue description is pasted below:

There are a variety of subsystems within Torque that I think would benefit from using the standard library more. While there would be some overhead here in terms of implementing the changes, I believe in the long run they would drastically reduce the maintenance costs for the engine, as well as the potential for bugs in various subtle implementation issues.

The example that's currently sticking out to me is the huge amount of manual reference counting machinery that could be elided through appropriate use of `shared_ptr` (and probably some edge cases where using reference types, `weak_ptr`, and `unique_ptr` might be more appropriate entirely).

Similarly, keeping around (and maintaining) custom implementations of `vector`, `map`, etc, seems like a poor use of development investment, unless there are specific performance reasons for implementing our own.

**Comment by JeffProgrammer** [comment]
Don't think this is really an issue. There's pros/cons for STL replacement and this discussion has happened many times in the past. Current way we see it for future is to keep using what's built in as 'whats broke don't fix it' but we're not against STL for contributions.

**Comment by dottools** [comment]
Looking into https://github.com/electronicarts/EASTL wouldn't be a bad idea if we had to use a particular STL. Wouldn't have to use the toolchain provided STL.
