### ISSUE TITLE
Main menu doesn't allow null audio device

### ISSUE THREAD

**Issue by rextimmy** [TorqueGameEngines/Torque3D#445]
Main menu settings doesn't list the NULL audio device, therefore it can't be selected.

**Comment by dottools** [comment]
That's by design as NULL device is only suitable for servers. Stand alone/single player and game clients shouldn't be making NULL audio device available anymore than NULL graphics device.

**Comment by rextimmy** [comment]
It has been in there since version 1.0 of T3D, I have personally spent hundreds upon hundreds of hours running t3d clients with the null audio device.
