### ISSUE TITLE
can't compile 4.0 on LinuxMint 20, because no `pthread_yield_np()`

### ISSUE THREAD

**Issue by SuperUserNameMan** [TorqueGameEngines/Torque3D#501]
Hello,

Compilation of version dev 4.0 fails here :

` convexDecomp/NvThreadConfig.cpp:137:4: error: ‘pthread_yield_np’ was not declared in this scope; did you mean ‘pthread_yield’? `

System : LinuxMint 20 Ulyana, 64bits

edit : related to PR #499

**Comment by SuperUserNameMan** [comment]
incoming PR here #507

**Comment by Azaezel** [comment]
largely addressed, but leaving this ticket live in case of issues related to the commit.

**Comment by JeffProgrammer** [comment]
are we good to close this now?
