### ISSUE TITLE
Case-sensitive filenames issues with Linux !

### ISSUE THREAD

**Issue by SuperUserNameMan** [TorqueGameEngines/Torque3D#502]
Hello,

Windows developers, please, don't forget Linux filenames are case-sensitive !

Version 4.0 could not run out of the box with default template because of these 2 scripts filenames :

````
./game/core/Core.module
./game/core/Core.tscript
````

Linux was looking for lowercase filenames.

Note : I have not fully tested yet, so it's possible some others case-sensitive filenames issues exists elsewhere.

-----------

edit : updated list of files causing issues :

- [x] ` core/Core.modul `
- [x] ` core/Core.tscript `
- [x] ` tools/assetBrowser/guis/AssetImportConfigEditor.gui `
- [x] ` tools/assetBrowser/guis/GameObjectCreator.gui `
- [x] ` tools/Tools.tscript `

**Comment by Azaezel** [comment]
Reminder note for our win-side devs: as an assist for this, full debug generates reports of the form
`Linux Compatibility Warning Core.tscript != core.tscript` when a conflict is found.

**Comment by Azaezel** [comment]
So for a more concrete answer, looks like causation for core at least is due to a mismatch in the directory, filename, and 
`ModuleDatabase.scanModules( "core", false );` entry in main.tscript. tempfix there will be 
`ModuleDatabase.scanModules( "Core", false );`

**Comment by SuperUserNameMan** [comment]
Unfortunately, ` ModuleDatabase.scanModules( "Core", false ); ` does not fix here :-(

Only renaming ` ./game/core/Core.* ` to ` ./game/core/core.* ` works.

**Comment by SuperUserNameMan** [comment]
These scripts also have conflicting letter-case :

- [x] ` tools/assetBrowser/guis/AssetImportConfigEditor.gui `

- [x] ` tools/assetBrowser/guis/GameObjectCreator.gui `

edit : their first letter should be lowercase according to this script :

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/tools/assetBrowser/main.tscript#L58

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/tools/assetBrowser/main.tscript#L63

**Comment by SuperUserNameMan** [comment]
- [x] Same with ` tools/Tools.tscript `
