### ISSUE TITLE
Linux : v4.0 compiled Release executable too large

### ISSUE THREAD

**Issue by SuperUserNameMan** [TorqueGameEngines/Torque3D#503]
Hello,

I don't know if it really count as a bug, but if I compile Torque3D in Release mode following the [wiki instructions](http://wiki.torque3d.org/coder:compiling-in-linux) the size of the executable i get is ~450 MB large.

I had to use a ` strip --strip-all ./MyExecutable ` command to slim it down to ~65 MB.

I'm on LinuxMint20 64bits, with gcc 9.3.0.

I've read somewhere that ` -s ` could be sent to `gcc` through the makefile ...

Does it count as a bug ? or is it something obvious I should have done by myself anyway ?

**Comment by Azaezel** [comment]
nah, definitely a bug. one we've been tryin to track down on and off for a while now.

**Comment by SuperUserNameMan** [comment]
I'm total n00b with ` cmake ` and ` makefiles `, but after what I managed to decipher, I'd say that ` torque3d.cmake ` could need some cleanup and comments.

So, if you do that, this works :
` cmake ../../../.. -DTORQUE_APP_NAME=MyApp -DCMAKE_BUILD_TYPE=Release -DCXX_FLAG32=-Wl,-s `

A stripped exec will be generated.

However, on linux, `-DCMAKE_BUILD_TYPE=Release` seems pointless since it seems to be overridden later here with `TORQUE_BUILD_TYPE` :
https://github.com/TorqueGameEngines/Torque3D/blob/83b0432283d6584328956bf3bbdb8382945c0e31/Tools/CMake/torque3d.cmake#L235-L247

And just before, `TORQUE_BUILD_TYPE` is forced to `Debug` here :
https://github.com/TorqueGameEngines/Torque3D/blob/83b0432283d6584328956bf3bbdb8382945c0e31/Tools/CMake/torque3d.cmake#L154-L163

I don't understand why ...

----------

So, here is my hack :

Here,
https://github.com/TorqueGameEngines/Torque3D/blob/83b0432283d6584328956bf3bbdb8382945c0e31/Tools/CMake/torque3d.cmake#L30-L39

I add this after line 35 :
````cmake
      if (CMAKE_BUILD_TYPE STREQUAL "Release")
        set(CXX_FLAG32 "${CXX_FLAG32} -Wl,-s")
      endif()
````

and voilà :

````cmake
if(UNIX)
    if(NOT CXX_FLAG32)
        set(CXX_FLAG32 "")
    endif()
    #set(CXX_FLAG32 "-m32") #uncomment for build x32 on OSx64

    if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
	  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CXX_FLAG32} -Wundef -msse -pipe -Wfatal-errors -Wno-return-type-c-linkage -Wno-unused-local-typedef ${TORQUE_ADDITIONAL_LINKER_FLAGS}")
      set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CXX_FLAG32} -Wundef -msse -pipe -Wfatal-errors -Wno-return-type-c-linkage -Wno-unused-local-typedef ${TORQUE_ADDITIONAL_LINKER_FLAGS}")
    else()
      # default compiler flags
      if (CMAKE_BUILD_TYPE STREQUAL "Release")
        set(CXX_FLAG32 "${CXX_FLAG32} -Wl,-s")
      endif()

      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CXX_FLAG32} -Wundef -msse -pipe -Wfatal-errors -no-pie ${TORQUE_ADDITIONAL_LINKER_FLAGS} -Wl,-rpath,'$ORIGIN'")
      set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CXX_FLAG32} -Wundef -msse -pipe -Wfatal-errors ${TORQUE_ADDITIONAL_LINKER_FLAGS} -Wl,-rpath,'$ORIGIN'")
     
    endif()    

    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
endif()
````

`cmake ../../../.. -DTORQUE_APP_NAME=MyApp -DCMAKE_BUILD_TYPE=Release` will generates a stripped exec in Linux.
