### ISSUE TITLE
list of missing files

### ISSUE THREAD

**Issue by SuperUserNameMan** [TorqueGameEngines/Torque3D#512]
Here is a list of missing scripts and assets :

---

- [ ] `core/rendering/scripts/terrainSettings.tscript`, required here :

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/core/rendering/Core_Rendering.tscript#L29

----

- [ ] `data/Blockout_Basics/*` required here : 

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/tools/assetBrowser/guis/assetPreviewButtonsTemplate.gui#L34

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/tools/assetBrowser/guis/assetPreviewButtonsTemplate.gui#L166

---

- [ ] `tools/assetBrowser/searchCollectionSets.xml` required here :

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/tools/assetBrowser/main.tscript#L27

---

- [ ] ` tools/gui/inspector-style-rollout-dark ` and all other files specified in each singleton's ` bitmap= `, here :

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/tools/gui/profiles.ed.tscript#

---

- [ ] ` tools/gui/postFxManager.gui ` required here :

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/tools/gui/guiDialogs.ed.tscript#L37

---

- [ ] ` tools/assetBrowser/guis/assetImportConfigEditor.gui ` required here :

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/tools/assetBrowser/main.tscript#L63

---

- [ ] ` tools/assetBrowser/guis/importTemplateModules.gui ` required here :

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/tools/assetBrowser/main.tscript#L67

---

- [ ] ` tools/componentEditor/scripts/stateMachineEditor.ed.tscrip ` required here :

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/tools/componentEditor/main.tscript#L25

---

- [ ] ` tools/componentEditor/gui/stateMachineDlg.ed.gui ` required here :

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/tools/componentEditor/main.tscript#L30

---

**Comment by WageCrusader** [comment]
Appears resolved by Areloch's commit above.
