### ISSUE TITLE
v3.10.1 : terrain editor : mousedown dragging bug

### ISSUE THREAD

**Issue by SuperUserNameMan** [TorqueGameEngines/Torque3D#516]
Hello,

I was testing Terrain editing with 3.10.1 on LinuxMint20 x64.

Raising and lowering terrain using mouse dragging (keep mouse button down and move the mouse), the terrain is raised/lowered both inside the pink circle cursor AND at the center of the map.

See picture below : I was raising terrain on the left, and a large column erected by itself in the middle of the map ....... (there is a pun, but I'm serious, it's a real bug)

![image](https://user-images.githubusercontent.com/9801802/126500083-cb2f2fd9-e577-41d7-a05a-2f305d0d654e.png)

I thought it was because I have dual-monitor setup, but it does that in single-monitor.
Then I thought maybe it's because I'm on a laptop (mouse + trackpad), but it does that with the trackpad alone too.

**Comment by SuperUserNameMan** [comment]
oups, seems to be #78

**Comment by Azaezel** [comment]
https://github.com/TorqueGameEngines/Torque3D/pull/462

**Comment by SuperUserNameMan** [comment]
Oh thanks ! I'm glad there was a PR already, because I was light years away from pinpointing the solution ...

So to keep the v3.10.1 code coherence, the backport translates to :
````C++
   if (dStrcmp(getCurrentAction(), "paintMaterial") != 0)
   {
      if (mMouseDown)
         return;
   }
````

Should I close this issue ?
Do you plan new v3 updates release ?

**Comment by Azaezel** [comment]
> Should I close this issue ?

If that works for you, by all means,

> Do you plan new v3 updates release ?

No, we're (hopefully finally) rounding the bend on the 3.x to 4.0 conversion protocols/wizard though.
