### ISSUE TITLE
TGEA + PlugIns + Editors

### ISSUE THREAD

**Issue by anonimo82** [TorqueGameEngines/Torque3D#519]
Hello everyone. @JeffProgrammer 
I brushed up some old software I bought back in 2006 (Adobe Creative Suite CS2 and 3D Studio MAX 9, among others) and I'd like to toy with TGEA, which I bought as well, but I don't have the download link nor the downloaded archive.
I'd also like plugins for Photoshop (Normal Map Plugin) and 3D Studio MAX (Exporters), plus the "canonical" editors:
 - DSQ Tweaker
 - Constructor
 - Show Tool Pro
 - Torsion
 - L3DT

I also bought, back at the time:
 - Yack Pack
 - Game Mechanics Kit
 - Plastic Tweaker
 - Verve
 - Universal AI Starter Kit
 - Animations Mega Pack
 - 3D Action Adventure Kit

Please, is it any way to have them back?
I didn't try Torque3D yet, so, maybe it already have all of the above?

Thanks in advance for any help.

**Comment by dottools** [comment]
Torsion was open sourced. Here's a fork of the repository where somebody made a successful, and improved, build of the program: https://github.com/HumanGamer/Torsion/releases

All the others I believe you can still retrieve from http://garagegames.com provided you remember your account login. However you'll probably run into activation issues when installing several of those programs. I think Constructor is one of them.

**Comment by anonimo82** [comment]
Well, I'm Berserk on GarageGames, but I don't remember my password and I no longer have my email address I had back at the time.
Is it there any way to get in touch with a site admin?

**Comment by lukaspj** [comment]
@anonimo82 is there any reason you don't upgrade to Torque3D? (Just curious)

**Comment by anonimo82** [comment]
Nostalgia, and I wouldn't make anything commercial, just want to have fun.
Edit: Can't I receive the installers in some way? Maybe from some file hosting service?
If so, please, get in touch with me: 18101982.ia@gmail.com

Thanks in advance for anything.

**Comment by anonimo82** [comment]
Any help?

**Comment by HumanGamer** [comment]
I have a collection of TGE and TSE/TGEA. I have almost all versions. I just don't think there is any way I can legally distribute it to you..

**Comment by JeffProgrammer** [comment]
Hi there,

We cannot give out previous versions of the engine. You would have to contact someone from GarageGames on their website. 

My suggestion is to use Torque3D as all of those products haven't been updated in years, and I doubt GarageGames even sells or supports any of them anymore.

**Comment by anonimo82** [comment]
Can I at least recover my password on GarageGames?

**Comment by JeffProgrammer** [comment]
We have no control over that. None of us have any administrative powers of GarageGames. GarageGames hasn't been involved with Torque3D for many years now.
