### ISSUE TITLE
Better checking for redundant FBO binding with Glad

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#56]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/1833)).
The issue was originally created by @Areloch and had a total of 0 comments that may contain additional information. The original issue description is pasted below:

A minor issue with the Glad implementation was that on Windows machines with intel graphics, it would trip openGL warns about redundant FBO bindings which may have a theoretical performance impact. 

We didn't find enough of an impact to be concerned, and no other GPU/platform exhibited this behavior, so we just squelched the warn for now, but a revisit of the FBO binding code at some point wouldn't be a bad idea.

**Comment by JeffProgrammer** [comment]
non issue, will be cleaned up in revamp of gfx.
