### ISSUE TITLE
OpenGL bug on parallax terrain

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#71]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/1635)).
The issue was originally created by @Duion and had a total of 1 comments that may contain additional information. The original issue description is pasted below:

There is a graphic bug when you are in OpenGL rendering and looking at terrain textures with parallax, you can sometimes see little hairlines between the polygons, does not matter if parallax is on or not, it happens when you activate the terrain textures for parallax.
It looks like this: http://i.imgur.com/og1Xoub.jpg

**Comment by JeffProgrammer** [comment]
With the new PBR renderer is this still a thing? cc @Azaezel @Areloch
