### ISSUE TITLE
Light animations

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#8]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/2302)).
The issue was originally created by @Bloodknight and had a total of 0 comments that may contain additional information. The original issue description is pasted below:

Light animations need an offset value, the AnimationPhase is not intuitive and its also poorly explained, the numbers may as well be magic numbers,

I could go digging into the code, but that's still not ideal especially for those working without the code. 

Assuming the lights are 'activated' at a point in time after the mission loads, a value up to what? 3000ms would give enough variability for a dozen lights in the same space.

**Comment by Azaezel** [comment]
https://github.com/TorqueGameEngines/Torque3D/blob/ac395775439985cc7332e777485d252055bdb042/Engine/source/afx/ce/afxLightBase_T3D.cpp#L127 covers the request: https://cdn.discordapp.com/attachments/580242040730943509/721427106436874250/unknown.png

**Comment by Azaezel** [comment]
actually, so i don't jump the gun: for clarity, is this a request for clarification on the functionality as it represents an offset percentile of the total sequence, or for an actual new feature?
