### ISSUE TITLE
Please help to fix the GCC bug

### ISSUE THREAD

**Issue by ackelcn** [TorqueGameEngines/Torque3D#810]
I read the commit that workarounds a gcc bug:
https://github.com/TorqueGameEngines/Torque3D/commit/1b55dce613dab6122aa7660d546328e83b103534

I notice that this simple fix workarounds a crash at startup. 
https://github.com/TorqueGameEngines/Torque3D/pull/559

This bug looks quite important, and it can cause crashes to other projects. I have filed this problem to gcc:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105881

Would you please provide more details? If GCC fixes this bug, this problem can be fully fixed.

**Comment by apinski-cavium** [comment]
This is NOT a GCC bug. Rather it is a bug which depends on stuff like:
```
         // mLength is initialized by operator new()
```
inside `StringData( const StringChar* data, bool interned = false )`. Before the constructor, nothing can be assumed to be initialized so the store for mLength which was in the "operator new" is being deleted as being dead.

You can workaround this undefined code by using -flifetime-dse=1 as described in https://gcc.gnu.org/onlinedocs/gcc-12.1.0/gcc/Optimize-Options.html#index-flifetime-dse :
```
To preserve stores before the constructor starts (e.g. because your operator new clears the object storage) but still treat the object as dead after the destructor, you can use -flifetime-dse=1. The default behavior can be explicitly selected with -flifetime-dse=2. -flifetime-dse=0 is equivalent to -fno-lifetime-dse.
```

**Comment by jwakely** [comment]
This has also been documented at https://gcc.gnu.org/gcc-6/porting_to.html#flifetime-dse since GCC 6 started to optimize away the undefined writes to members of an object that doesn't exist yet.

**Comment by jwakely** [comment]
> You can workaround this undefined code by using -flifetime-dse=1

Actually I think this code is so buggy it needs `-fno-lifetime-dse`, at least when `TORQUE_ENABLE_ASSERTS` or `TORQUE_DEBUG` is defined, because `operator delete` assumes it can access a members of the string even though the destructor has already finished. Line 513 uses `mRefCount` and line 516 uses `mLength`:

https://github.com/TorqueGameEngines/Torque3D/blob/53aea82614197cff139d8d9314165fd189830a22/Engine/source/core/util/str.cpp#L510-L521

**Comment by dottools** [comment]
@jwakely is correct per https://en.cppreference.com/w/cpp/memory/new/operator_delete

The reference counting check and debug handling should be done in class destructor not in operator delete.
