### ISSUE TITLE
World Editor is missing in T3d 4.0 Preview

### ISSUE THREAD

**Issue by lowlevelsoul** [TorqueGameEngines/Torque3D#829]
As the subject says. The ability to span / start the editor is completely missing. The log reports that the console function "fastLoadWorldEdit" isn't there. 

It's not present in the engine source, and I can't find it in any of the script files. In fact, it seems that the editor script files are completely missing.

**Comment by Azaezel** [comment]
Any additional data? Just did a fresh rebuild from scratch, and got into the world editor both from the main menu button and hitting F11 after compiling and building the install target the once to flip files into place.

**Comment by lowlevelsoul** [comment]
Ok, so I did the install target which was what was missing. I haven't used Torque for a long long time, so I wasn't aware of having to do dp this build step. The editor seems to be working fine. now.
