### ISSUE TITLE
Debug Crashes Torque

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#84]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/1364)).
The issue was originally created by @avarisclari and had a total of 2 comments that may contain additional information. The original issue description is pasted below:

On Linux compiled with GCC:
I don't know what's causing it, but if I choose debug when there's an error, torque just crashes. If I choose ignore, it's fine. I used gdb to try to trace the crash, gist below:
https://gist.github.com/avarisclari/d758bb054b2d058b786e

**Comment by JeffProgrammer** [comment]
pretty old issue, and we got folks using Linux, so closing unless we get new crashes.
