### ISSUE TITLE
Support for OpenGL's 3D textures

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#94]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/1266)).
The issue was originally created by @LuisAntonRebollo and had a total of 3 comments that may contain additional information. The original issue description is pasted below:

See [this assert](https://github.com/GarageGames/Torque3D/blob/1c580f5a5f2fc93a7432316275ae394d71dfc519/Engine/source/gfx/gl/gfxGLTextureObject.cpp#L60)

**Comment by JeffProgrammer** [comment]
Is this still an issue? when should we ever 'lock' a 3d texture? We should upload faces and then blit on the gpu in vram.
