### ISSUE TITLE
Crash in player::setState if no LandAnim

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#96]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/1228)).
The issue was originally created by @SteveYorkshire and had a total of 1 comments that may contain additional information. The original issue description is pasted below:

There's a crash if the player has no landAnim when player::setState switches to recover state. Crash is caused by it trying to get the length of the non-existant animation.

> ```
>           if (mDataBlock->landSequenceTime > 0.0f)
>            {
>               // Use the land sequence as the basis for the recovery
>               setActionThread(PlayerData::LandAnim, true, false, true, true);
>               F32 timeScale = mShapeInstance->getDuration(mActionAnimation.thread) / mDataBlock->landSequenceTime;
>               mShapeInstance->setTimeScale(mActionAnimation.thread,timeScale);
>               mRecoverDelay =  mDataBlock->landSequenceTime;
>            }
> ```

Solution: fixitfixitfixit - not sure which is best, either go through the table of animations and make an extra if(isLandAnim == false) check or whether to do this once on PlayerData::preLoad() like it does using run animation if it cannot find a sprint one.
Setting landTimeSequence to 0 in the datablock also avoids the crash but it hardly an elegant solution.

**Comment by mynamebew3001** [comment]
```
Duplicate of #
```

**Comment by mynamebew3001** [comment]
@jamesu
