### ISSUE TITLE
Library/Controls Palette is missing from GUI Editor, making it impossible to create new controls in a GUI.

### ISSUE THREAD

**Issue by dooderino** [TorqueGameEngines/Torque3D#962]

**Comment by Azaezel** [comment]
A few example cases of gui authoring: https://www.youtube.com/watch?v=qF2ychSMvj0
that being said, the 4.1 release is mostly going to be focused on better tooling presentation, so by all means, feel free to go into further detail.

**Comment by dooderino** [comment]
> A few example cases of gui authoring: https://www.youtube.com/watch?v=qF2ychSMvj0
> 
> that being said, the 4.1 release is mostly going to be focused on better tooling presentation, so by all means, feel free to go into further detail.

Ah, I have been using the docs from 3.5.1 and did not know that you can do this from the Asset Browser. I will close the issue.

**Comment by Azaezel** [comment]
Well, again if anything does get you turned around do by all means jot a note down, or hop by the discord where we've got a dedicated conversation on the topic https://discord.gg/HC4x4qk7
